[workspace]
members = [
    "tokio-native-tls",
    "tokio-rustls",
    "tokio-rustls/examples/client",
    "tokio-rustls/examples/server"
]

[patch.crates-io]
rustls = { git = 'https://github.com/johanvos/rustls', branch = 'ech-15' }
